import { HttpStatus } from '@nestjs/common';

import type { AppErrorCode } from './app-error';

export const ERROR_HTTP_STATUS: Record<AppErrorCode, number> = {
  NOT_FOUND: HttpStatus.NOT_FOUND,
  BAD_REQUEST: HttpStatus.BAD_REQUEST,
  CONFLICT: HttpStatus.CONFLICT,
  VALIDATION: HttpStatus.UNPROCESSABLE_ENTITY,
  FORBIDDEN: HttpStatus.FORBIDDEN,
  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  INTERNAL: HttpStatus.INTERNAL_SERVER_ERROR,
  QA_PROFILE_INVALID: HttpStatus.BAD_REQUEST,
  QA_PROFILE_NOT_READY: HttpStatus.CONFLICT,
  QA_SANDBOX_REQUIRED: HttpStatus.BAD_REQUEST,
  QA_SANDBOX_MISMATCH: HttpStatus.FORBIDDEN,
  QA_CAPABILITY_UNKNOWN: HttpStatus.BAD_REQUEST,
  QA_CONTEXT_AMBIGUOUS: HttpStatus.CONFLICT,
  QA_CONTEXT_INVALID: HttpStatus.BAD_REQUEST,
  QA_RUN_STATE_INVALID: HttpStatus.CONFLICT,
  QA_STEP_STATE_INVALID: HttpStatus.CONFLICT,
  QA_SYSTEM_VERSION_UNAVAILABLE: HttpStatus.BAD_REQUEST,
  QA_EXECUTION_FAILED: HttpStatus.INTERNAL_SERVER_ERROR,
  QA_REVIEW_FAILED: HttpStatus.INTERNAL_SERVER_ERROR,
  QA_CLONE_CONFIRMATION_REQUIRED: HttpStatus.BAD_REQUEST,
};
